export function SettingsReference(){return <main className="dk-panel"><header><small>SYSTEM</small><h1>Settings</h1></header><nav>{["Appearance","Feedback","Display","System","Controller","Audio","Network","Bluetooth"].map(x=><span className={x==="Controller"?"on":""}>{x}</span>)}</nav><section className="ps-glass"><small>CONTROLLER</small><Row label="Trackpad swipe sensitivity" value="1.0×" slider/><Row label="Cursor sensitivity" value="1.6×"/><Row label="Controller haptics" value="On"/></section></main>}
export function SearchReference(){return <main className="dk-panel"><small>LIBRARY</small><h1>Search</h1><div className="ps-glass dk-search">Search apps, games, launchers…</div><div className="dk-keys">Q W E R T Y U I O P<br/>A S D F G H J K L<br/>Z X C V B N M ⌫</div></main>}
export function KeyboardReference(){return <main className="dk-panel"><small>INPUT</small><h1>Virtual keyboard</h1><div className="dk-keys">Q W E R T Y U I O P<br/>A S D F G H J K L<br/>Z X C V B N M ⌫<br/>──────── SPACE ────────</div></main>}
export function YouTubeReference(){return <main className="dk-youtube"><button>◯ Back</button><div><b>▶</b><h1>YouTube</h1><p>Ready to stream on the big screen</p></div></main>}
export function IdleReference(){return <main className="dk-idle"><b>PS·5 MODE</b><p>Press × to wake</p></main>}
export function QuickReferences(){return <><aside className="ps-glass dk-pop"><small>QUICK SETTINGS</small><h2>Wi‑Fi</h2><Row label="Home-5G" value="Connected · 82%"/></aside><aside className="ps-glass dk-pop"><small>READY TO LAUNCH</small><h2>Netflix</h2><p>× Launch · ◯ Cancel</p></aside></>}
function Row({label,value,slider}:{label:string;value:string;slider?:boolean}){return <div className="dk-row"><span>{label}</span>{slider&&<i/>}<b>{value}</b></div>}

export const panelReferenceCss=`.dk-panel{padding:6cqh 7cqw;background:var(--ps-ground);color:var(--ps-text);min-height:100%}.dk-panel h1{font-size:5.5cqh;margin:1cqh 0}.dk-panel nav{display:flex;flex-wrap:wrap;gap:.5cqw;margin-bottom:3cqh}.dk-panel nav span{padding:.8cqh 1cqw;color:var(--ps-muted)}.dk-panel nav .on{background:#ffffff1f;border-radius:1cqh;color:#fff}.dk-panel section{width:62cqw;padding:2cqh;border-radius:2cqh}.dk-row{display:flex;gap:1cqw;align-items:center;padding:1.4cqh 1.2cqw;margin-top:.7cqh;background:#ffffff0d;border-radius:1cqh}.dk-row span{flex:1}.dk-row i{width:11cqw;height:.55cqh;background:linear-gradient(90deg,#fff 54%,#ffffff33 54%);border-radius:999px}.dk-search{padding:1.6cqh 2cqw;border-radius:1.7cqh;width:62cqw;color:#ffffff80}.dk-keys{margin-top:3cqh;font-size:2cqh;line-height:2.4;letter-spacing:.4cqw}.dk-youtube,.dk-idle{min-height:100%;display:grid;place-items:center;text-align:center;background:#07090e;color:#fff}.dk-youtube b{font-size:10cqh;color:#e50914}.dk-youtube h1{font-size:5cqh}.dk-idle b{font-size:3cqh;letter-spacing:.25em}.dk-idle p{color:var(--ps-muted)}.dk-pop{padding:2cqh;border-radius:2cqh;width:30cqw}`;
